name: tic_tac_toe_bridge
description: The bridge to work with the server for Tic Tac Toe with which you can create your own client or bot for the game.
version: 0.1.1+2
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ">=4.0.6 <5.0.0"
  crypto: ">=3.0.2 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
