name: tic_tac_toe_bridge
description: Bridge for the tic tac toe game backend.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ">=4.0.6 <5.0.0"
  device_info_plus: ">=3.2.3 <4.0.0"
  crypto: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
